"""add_organization_subscription_model

Revision ID: 99477afd4701
Revises: b8ba47cd3f7a
Create Date: 2026-07-25 12:19:08.471374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99477afd4701'
down_revision: Union[str, Sequence[str], None] = 'b8ba47cd3f7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_subscriptions',
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('kaspi_order_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('org_id')
    )
    op.create_index(op.f('ix_organization_subscriptions_kaspi_order_id'), 'organization_subscriptions', ['kaspi_order_id'], unique=False)
    op.create_index(op.f('ix_organization_subscriptions_org_id'), 'organization_subscriptions', ['org_id'], unique=False)
    op.create_index(op.f('ix_organization_subscriptions_stripe_customer_id'), 'organization_subscriptions', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_organization_subscriptions_stripe_subscription_id'), 'organization_subscriptions', ['stripe_subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organization_subscriptions_stripe_subscription_id'), table_name='organization_subscriptions')
    op.drop_index(op.f('ix_organization_subscriptions_stripe_customer_id'), table_name='organization_subscriptions')
    op.drop_index(op.f('ix_organization_subscriptions_org_id'), table_name='organization_subscriptions')
    op.drop_index(op.f('ix_organization_subscriptions_kaspi_order_id'), table_name='organization_subscriptions')
    op.drop_table('organization_subscriptions')
    # ### end Alembic commands ###
